name: Wtube

source:
  name: ImageFolderWatcherSource
  args:
    path: 'logs/test/images'

preprocess:
  name: YoloOnnxPreprocessor
  args:
    model_width: 640
    model_height: 640

inference:
  name: YoloOnnxInference
  args:
    model_weights: "wtube/inference/detectors/yolo/weights/base_y8m_apv-dataset-v4a_run1.onnx"

postprocess:
  name: YoloOnnxPostprocessor
  args: {}
